# Данный workflow демонстрирует изменение себя

name: Модификация себя

on:
  workflow_dispatch:

jobs:
  RABOTA:
    runs-on: ubuntu-latest

    name: Демонстрация модификация себя

    steps:

    - name: Модифицируем себя

      # Требуется для gh pr
      env:
        GH_TOKEN: ${{ github.token }}

      run: |
        git clone https://github.com/${{github.repository}} this_repo

        # Сохраняем текущее время в переменную NOW
        NOW=$(date)

        # Дописываем время в конец файла main.yml
        echo "# $NOW " >> this_repo/.github/workflows/main.yml

        # Автор коммита
        git config --global user.email [бот]@users.noreply.github.com
        git config --global user.name [Бот]

        # Отправляем изменения в текущий репозиторий
        cd this_repo
        git add -A
        git commit -m "Update $NOW" || : # Создаём коммит и перехватываем ошибку, если в репозитории нет изменений

        # Такой способ использовать нельзя, так как workflow поменялся, а значит и токен поменялся.
        # Будет ошибка
        # To https://github.com/GitHubExperiments/modify-itself
        #  ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/main.yml` without `workflows` permission)
        # error: failed to push some refs to 'https://github.com/GitHubExperiments/modify-itself'
        #git push https://.:${{github.token}}@github.com/${{github.repository}}

        # Используем PAT. У токена должна быть включена галочка "workflow"
        #git push https://${{secrets.GH_EXP_TOKEN}}@github.com/GitHubExperiments/modify-itself

        # А можно PR создать
        gh pr create --title 'Заголовок PR' --body 'Описание PR'

        cd ..
